<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="UTF-8">
		<title>BLOG</title>
		<link rel="stylesheet" href="normalize.css">
		<link rel="stylesheet" href="style.css">
		<link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
	</head>
	<body>
		<header>
			<nav>
				<ul class="menu">
					<li><a href="index.php">Accueil</a></li>
					<li><a href="admin.php">Admin</a></li>
					<li><a href="upload/indexs.php">Photos</a></li>
					<li><a href="#">Contact</a></li>
				</ul>
			</nav>	
		</header>

		<section>

			<h1>Mon BLOG</h1>
			<h2><a href="disconnect.php">Déconnexion</a></h2>
			
		<div class="page">

			<?php if(isset($error)){ echo $error;} ?>

			<h1>Connexion</h1>

			<br>
			<form action="admin.php" method="post">
			<label for="nom">Login:</label><br>
			<input type="text" name="nom" placeholder="Entrez votre login">
			<br>
			<label for="nom">Mot de passe:</label><br>
			<input type="password" name="pass" placeholder="Entrez votre mot de passe">
			<br>
			<br>
			<button type="submit">Envoyez</button>



			</form>
		</div>
		</section>
		
		<footer>
			
		</footer>
	</body>
</html>