<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<title>BLOG</title>
	</head>
	<body>
		<h1>Mon BLOG</h1>
	
		<div>
				<p>
					<?php echo $monpost['title']; ?> 
				</p>
				<p>
					<?php echo $monpost['content']; ?> 
				</p>
				<p>
					<?php echo $monpost['date_create']; ?> 
				</p>
				<p>
					<?php echo $monpost['author_id']; ?> 
				</p>	
		</div>
		
	</body>
</html>