<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="UTF-8">
		<title>BLOG</title>
		<link rel="stylesheet" href="normalize.css">
		<link rel="stylesheet" href="style.css">
		<link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
	</head>
	<body>
		<header>
			<nav>
				<ul class="menu">
					<li><a href="index.php">Accueil</a></li>
					<li><a href="admin.php">Admin</a></li>
					<li><a href="upload/indexs.php">Photos</a></li>
					<li><a href="#">Contact</a></li>
				</ul>
			</nav>
			
		</header>

		<section>

			<h1>Mon BLOG</h1>
			<h2><a href="registrer.php">Enregistrez-vous</a></h2>
			<p style="text-align: right;">créer un article ou laisser un commentaire</p>
			
		<div class="page">
				<p style="color: #006400 ">
					Titre: <?php echo $monpost['title']; ?> </a>
					
				</p>
				<p style="color: #006400 "> Mon Blog: </p>
				<p><?php echo $monpost['content']; ?> </p> 
				<p style="color: #006400 ">
					Date de Création: <?php echo $monpost['date_create']; ?> | Auteur: <?php echo $monpost['nom']; ?> 
				</p>
				<br>

		</div>
		</section>
		
		<footer>
			
		</footer>
	</body>
</html>