<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="UTF-8">
		<title>BLOG</title>
		<link rel="stylesheet" href="normalize.css">
		<link rel="stylesheet" href="style.css">
		<link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
	</head>
	<body>
		<header>
			<nav>
				<ul class="menu">
					<li><a href="index.php">Accueil</a></li>
					<li><a href="admin.php">Admin</a></li>
					<li><a href="upload/indexs.php">Photos</a></li>
					<li><a href="contact.php">Contact</a></li>
				</ul>
			</nav>
			
		</header>

		<section>

			<h1><a href="index.php">Mon BLOG</a></h1>
			<h2><a href="registrer.php">Enregistrez-vous</a></h2>
			<p style="text-align: right;">créer un article ou laisser un commentaire</p>
			
		<div class="page">
			<h3>
				Commentaires:
			</h3>

			<?php $mescomment=$comments->getCommentForAll($_GET['id']) ?>
				<?php  foreach ($mescomment as $comment): ?>
				<p><?php echo $comment['comment']; ?> | <?php echo $comment['date']; ?> </p>
				<?php endforeach; ?>
				<p>	

		</div>
		</section>
		
		<footer>
			
		</footer>
	</body>
</html>