<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="UTF-8">
		<title>BLOG</title>
		<link rel="stylesheet" href="normalize.css">
		<link rel="stylesheet" href="style.css">
		<link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
	</head>
	<body>
		<header>
			<nav>
				<ul class="menu">
					<li><a href="index.php">Accueil</a></li>
					<li><a href="admin.php">Admin</a></li>
					<li><a href="upload/indexs.php">Photos</a></li>
					<li><a href="contact.php">Contact</a></li>
				</ul>
			</nav>
			
		</header>

		<section>

			<h1><a href="index.php">Mon BLOG</a></h1>
			<h2><a href="registrer.php">Enregistrez-vous</a></h2>
			<p style="text-align: right;">créer un article ou laisser un commentaire</p>
			
		<div class="contact">
			<form id="contact" method="post" action="traitement_formulaire.php">
			<fieldset><legend>Vos coordonnées</legend>
			<p><label for="nom">Nom :</label><input type="text" id="nom" name="nom" tabindex="1" /></p>
			<p><label for="email">Email :</label><input type="text" id="email" name="email" tabindex="2" /></p>
			</fieldset>
 
			<fieldset><legend>Votre message :</legend>
			<p><label for="objet">Objet :</label><input type="text" id="objet" name="objet" tabindex="3" /></p>
			<p><label for="message">Message :</label><textarea id="message" name="message" tabindex="4" cols="30" rows="8"></textarea></p>
			</fieldset>
 
			<div style="text-align:center;"><input type="submit" name="envoi" value="Envoyer le formulaire !" /></div>
			</form>
		</div>
		</section>
		
		<footer>
			
		</footer>
	</body>
</html>