<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="UTF-8">
		<title>BLOG</title>
		<link rel="stylesheet" href="normalize.css">
		<link rel="stylesheet" href="style.css">
		<link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
	</head>
	<body>
		<header>
			<nav>
				<ul class="menu">
					<li><a href="index.php">Accueil</a></li>
					<li><a href="admin.php">Admin</a></li>
					<li><a href="upload/indexs.php">Photos</a></li>
					<li><a href="#">Contact</a></li>
				</ul>
			</nav>
			
		</header>

		<section>

			<h1>Mon BLOG</h1>
			<h2><a href="registrer.php">Enregistrez-vous</a></h2>
			<p style="text-align: right;">créer un article ou laisser un commentaire</p>
			
		<div class="page">
			<?php  foreach ($mesposts as $post): ?>
				<p style="color: #006400 ">
					Titre: <a href="article.php?id=<?= $post['id']; ?>"><?php echo $post['title']; ?> </a>
					
				</p>
				<p style="color: #006400 "> Mon Blog: </p>
				<p><?php echo $post['content']; ?> </p> 
				<p style="color: #006400 ">
					Date de Création: <?php echo $post['date_create']; ?> | Auteur: <?php echo $post['nom']; ?> 
				</p>
				<br>
				<p>
					<!-- Nombre de commentaire: <?php // echo $comment['']; ?>  --> 
				</p>
				<p style="color: #006400 ">
					Commentaires:
				</p>
				<?php $mescomment=$comments->getCommentForPost($post['id']) ?>
				<?php  foreach ($mescomment as $comment): ?>
				<p><?php echo $comment['comment']; ?> | <?php echo $comment['date']; ?> </p>
				<?php endforeach; ?>
				<p>
					Voir  <a href="comment.phtml">pluus de commentaires</a>
				</p>

				<form action="comment.php" method="post">

					<input type="hidden" value="<?php echo $post['id']; ?>" name="id_post">

					<label for="comment">Laissez votre commentaire: </label>
					<br>
					<textarea name="comment" id="comment" cols="30" rows="5"></textarea>
					<br>
					<button type="submit" name="submit" value="3">Envoyez</button>
					<br>
				</form>
				<br>

			<?php endforeach; ?>
		</div>

		<div class="pagenext">

			<ul>
				<li>
					<a href="index.php?page=

					<?php if($page<=1) 
						echo 1;
					else 
						echo $page-1 ?>
					">Prev
					</a>
				</li>
					
				<li><a href="index.php?page=<?= $page+1 ?>">Next</a></li>
			</ul>
	
		</div>
		</section>

		<footer>
			
		</footer>
	</body>
</html>
