<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="UTF-8">
		<title>BLOG</title>
		<link rel="stylesheet" href="normalize.css">
		<link rel="stylesheet" href="style.css">
		<link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
	</head>
	<body>
		<header>
			<nav>
				<ul class="menu">
					<li><a href="index.php">Accueil</a></li>
					<li><a href="admin.php">Admin</a></li>
					<li><a href="upload/indexs.php">Photos</a></li>
					<li><a href="contact.php">Contact</a></li>
				</ul>
			</nav>
			
		</header>

		<section>

			<h1><a href="index.php">Mon BLOG</a></h1>
			<h2><a href="registrer.php">Enregistrez-vous</a></h2>
			<p style="text-align: right;">créer un article ou laisser un commentaire</p>
			
		<div class="page">
			<?php  foreach ($mesposts as $post): ?>
				<h3>
					<img src="img/green-flower-hi.png" alt="flower" height="42" width="42"> Titre: <a href="article.php?id=<?= $post['id']; ?>"><?php echo $post['title']; ?> </a> 
				</h3>
				<h3> Mon Blog: </h3> 
				<p><?php echo substr ($post['content'],0,400)."<br>"."Voir plus..."; ?> <a href="article.php?id=<?= $post['id']; ?>"><?php echo $post['title']; ?> </a></p>
				<p style="color: #006400 ">
					Date de Création: <?php echo $post['date_create']; ?> | Auteur: <?php echo $post['nom']; ?> 
					<?php if(isset($_SESSION['id'])==true): ?>
					| <a href=" edit.php?id=<?= $post['id']; ?>"><img src="img/edit-button.png" alt="delete" height="32" width=""></a> | <a onclick="return confirm('Etes vous sure de vouloir supprimer cet article?')" href="delete.php?id=<?= $post['id']; ?>"><img src="img/deletebutton.png" alt="delete" height="32" width="62"></a>
				<?php endif ?>
				</p>
				<br>
				<p>
					<img src="img/blue-tag-icon.png" alt="tag" height="32" width="32">Tags:
				</p>

				<h3 >
					Commentaires:
				</h3>

				<?php $mescomment=$comments->getCommentForPost($post['id']) ?>
				<?php  foreach ($mescomment as $comment): ?>
				<p><?php echo $comment['comment']; ?> | <?php echo $comment['date']; ?> </p>
				<?php endforeach; ?>
				<p>
					Voir  <a href="commentplus.php?id=<?= $post['id'] ?>">plus de commentaires</a> | Nombre de commentaire: <?php echo $numberpage=$comments->getNumberOfPage($post['id']); ?>
				</p>

				<form action="comment.php" method="post">

					<input type="hidden" value="<?php echo $post['id']; ?>" name="id_post">
					<input type="hidden" value="index" name="cible">

					<label for="comment">Laissez votre commentaire: </label>
					<br>
					<textarea name="comment" id="comment" cols="30" rows="5"></textarea>
					<br>
					<button type="submit" name="submit" value="3">Envoyez</button>
					<br>
				</form>
				<br>

			<?php endforeach; ?>
		</div>
		
		</section>

		<footer>
			<div class="pagenext">

			<ul class="pagination">
				<li>
					<a href="index.php?page=

					<?php if($page<=1) 
						echo 1;
					else 
						echo $page-1 ?>
					">Prev
					</a>
				</li>
					
				<li><a href="index.php?page=<?= $page+1 ?>">Next</a></li>
			</ul>
	
		</div>
			
		</footer>
	</body>
</html>
