<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="UTF-8">
		<title>BLOG</title>
		<link rel="stylesheet" href="normalize.css">
		<link rel="stylesheet" href="style.css">
		<link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
	</head>
	<body>
		<header>
			<nav>
				<ul class="menu">
					<li><a href="index.php">Accueil</a></li>
					<li><a href="admin.php">Admin</a></li>
					<li><a href="#">Photos</a></li>
					<li><a href="#">Contact</a></li>
				</ul>
			</nav>
			
		</header>

		<section>

			<h1>Mon BLOG</h1>
			<h2><a href="registrer.php">Enregistrez-vous?</a></h2>
			<p style="text-align: right;">Pour rédiger un article sur mon blog</p>
			
		<div class="page">
			<?php  foreach ($mesposts as $post): ?>
				<p>
					Titre: <a href="article.php?id=<?= $post['id']; ?>"><?php echo $post['title']; ?> </a>
					
				</p>
				<p>
					Mon Blog: <br>
					<?php echo $post['content']; ?> 
				</p>
				<p>
					Date de Création: <?php echo $post['date_create']; ?> | Auteur: <?php echo $post['author_id']; ?> | Catégories: <?php echo $post['cat_id']; ?> 
				</p>
				<p>
					Nombre de commentaire: <?php echo $post['author_id']; ?>  
				</p>
				<br>

				<form action="comment.php" method="post">

					<label for="comment">Laissez votre commentaire: </label>
					<br>
					<textarea name="comment" id="comment" cols="30" rows="5"></textarea>
					<br>
					<button type="submit" name="submit" value="3">Envoyez</button>
					<br>
				</form>
				<br>

			<?php endforeach; ?>
		</div>
		</section>

		<footer>
			
		</footer>
	</body>
</html>