<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="UTF-8">
		<title>BLOG</title>
		<link rel="stylesheet" href="normalize.css">
		<link rel="stylesheet" href="style.css">
		<link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
	</head>
	<body>
		<header>
			<nav>
				<ul class="menu">
					<li><a href="index.php">Accueil</a></li>
					<li><a href="admin.php">Admin</a></li>
					<li><a href="#">Photos</a></li>
					<li><a href="about.php">Contact</a></li>
				</ul>
			</nav>
			
		</header>

		<section>

			<h1>Mon BLOG</h1>
			<h2><a href="login.php">Connexion</a></h2>
			
		<div class="page">
			<form action="admin.php" method="post">
			<label for="nom">Login:</label><br>
			<input type="text" name="name" placeholder="Entrez votre login">
			<br>
			<label for="nom">Mot de passe:</label><br>
			<input type="text" name="name" placeholder="Entrez votre mot de passe">
			<p><button type="submit" >Envoyez</button></p>

			</form>
		</div>
		</section>
		
		<footer>
			
		</footer>
	</body>
</html>