<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<title>BLOG</title>
	</head>
	<body>
		<h1>Mon BLOG</h1>
	
		<div>
			<?php  foreach ($mesposts as $post):	?>

				<p>
					<a href="article.php?id=<?= $post['id']; ?>"><?php echo $post['title']; ?> </a>
					
				</p>
				<p>
					<?php echo $post['content']; ?> 
				</p>
				<p>
					<?php echo $post['date_create']; ?> 
				</p>
				<p>
					<?php echo $post['author_id']; ?> 
				</p>
			<?php endforeach;  ?>

		</div>
		
	</body>
</html>