<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="UTF-8">
		<title>BLOG</title>
		<link rel="stylesheet" href="normalize.css">
		<link rel="stylesheet" href="style.css">
		<link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
		<!-- Place inside the <head> of your HTML -->
		<script type="text/javascript" src="tinymce/js/tinymce/tinymce.min.js"></script>
		<script type="text/javascript">
		tinymce.init({
		    selector: "textarea",
		    plugins: [
                "advlist autolink autosave link image lists charmap print preview hr anchor pagebreak spellchecker",
                "searchreplace wordcount visualblocks visualchars code fullscreen insertdatetime media nonbreaking",
                "table contextmenu directionality emoticons template textcolor paste textcolor colorpicker textpattern"
        ],

        toolbar1: "newdocument | bold italic underline strikethrough | alignleft aligncenter alignright alignjustify | styleselect formatselect fontselect fontsizeselect",
        toolbar2: "cut copy paste | searchreplace | bullist numlist | outdent indent blockquote | undo redo | link unlink anchor image media code | insertdatetime preview | forecolor backcolor",
        toolbar3: "table | hr removeformat | subscript superscript | charmap emoticons | print fullscreen | ltr rtl | spellchecker | visualchars visualblocks nonbreaking template pagebreak restoredraft",

        menubar: false,
        toolbar_items_size: 'small',

        style_formats: [
                {title: 'Bold text', inline: 'b'},
                {title: 'Red text', inline: 'span', styles: {color: '#ff0000'}},
                {title: 'Red header', block: 'h1', styles: {color: '#ff0000'}},
                {title: 'Example 1', inline: 'span', classes: 'example1'},
                {title: 'Example 2', inline: 'span', classes: 'example2'},
                {title: 'Table styles'},
                {title: 'Table row 1', selector: 'tr', classes: 'tablerow1'}
        ],

        templates: [
                {title: 'Test template 1', content: 'Test 1'},
                {title: 'Test template 2', content: 'Test 2'}
        ]
		 });
		
		</script>
		<style>
		div.photo{
				margin: 10px;
				padding: 10px;
				border: 0 none;
				overflow-x: hidden;
				overflow-y: scroll;
				width: 950px;
				height: 500px;

			}
			
		</style>
	</head>
	<body>
		<header>
			<nav>
				<ul class="menu">
					<li><a href="index.php">Accueil</a></li>
					<li><a href="admin.php">Admin</a></li>
					<li><a href="upload/indexs.php">Photos</a></li>
					<li><a href="contact.php">Contact</a></li>
				</ul>
			</nav>	
		</header>

		<section>

			<h1><a href="index.php">Mon BLOG</a></h1>
			<h2><a href="disconnect.php">Déconnexion</a></h2>
			
		<div class="text">

			<h1 style="text-align: center;">Bienveue sur votre page Admin</h1>
			<h3 style="color: #800000;">Bienvenue <?php echo $_SESSION['nom'] ?></h3>
			<br>
			<h2 style="text-align: left;">Rédigez votre article!</h2>
			<br>
		<form action="panel.php" method="post">
			<label for="nom">Votre Titre du blog</label><br>
			<input type="text" name="title" placeholder="Titre de votre article">
			<br><br>
		    <textarea  name="content" ></textarea>
			<br>
			<button type="submit">Publier</button>
		</form>
		</div>

		<div class="photo">
			<p>Glissez une photo de votre choix dans l'éditeur :</p>
			<?php foreach ($files as $file) {
			echo '<img src= '.'upload/pictures/'.$file.' />';
			} ?>
			<br>
		</div>
		    <br>
		
		</section>
		
		<footer>
			
			
		</footer>
	</body>
</html>

