<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<title>Photos</title>
		<link rel="stylesheet" href="/blogkanita/style.css">
		<link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
	</head>
	<body>
		<header>
			<nav>
				<ul class="menu">
					<li><a href="/blogkanita/index.php">Accueil</a></li>
					<li><a href="/blogkanita/admin.php">Admin</a></li>
					<li><a href="/blogkanita/upload/indexs.php">Photos</a></li>
					<li><a href="/blogkanita/contact.php">Contact</a></li>
				</ul>
			</nav>	
		</header>
	
	<section>
		<h1>Mes Photos</h1>
		<h3>Veuillez vous enregistrer pour <a href="/blogkanita/admin.php">upload</a></h3>
		<form action="upload.php" method="POST" enctype="multipart/form-data">
			<input type="file" name="userfile">
			<button type="submit" value="Envoyer le fichier" >Upload</button>
		</form>
		<br>
		<?php foreach ($files as $file) {
			echo '<img src= '.'pictures/'.$file.' />';
		} ?>

	</section>	
	</body>
</html>